### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by akashkathole7** [pablorenato1/Virtual-Assistant#1]
I want to talk with you please put your contact detail here.

**Comment by akashkathole7** [comment]
notification

**Comment by akashkathole7** [comment]
notification

**Comment by pablorenato1** [comment]
I am sorry I did not see it before, you could have contact-me by my linkedIn on my profile and also have my email

**Comment by akashkathole7** [comment]
What about , I am not understand?

**Comment by pablorenato1** [comment]
I just saw the issue regarding contact, and I'm truly sorry for not noticing it earlier.

**Comment by akashkathole7** [comment]
But what issue related

**Comment by pablorenato1** [comment]
I do not know you only open it with the title "Contact Us" and the "I want to talk with you please put your contact detail here." you sent it in August 1st
